version: '3'

services:
  web:
    build:
      context: ./web-server
      args:
        #Pasamos argumentos para el dockerfile
        php_version: ${PHP_VERSION}
    container_name: ${WEB_WERVER_NAME}
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ../www:/var/www/html
    restart: unless-stopped

  mysql:
    build:
      context: ./mysql
      args:
        #Pasamos argumentos para el dockerfile
        mysql_version: ${MYSQL_VERSION}
    container_name: ${DB_SERVER_NAME}
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${DB_VOLUMEN}:/var/lib/mysql
    restart: unless-stopped
    
